package org.acn.mcptaskservice;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.web.servlet.MockMvc;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@SpringBootTest
@AutoConfigureMockMvc
@TestPropertySource(properties = {
        "spring.datasource.url=jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1",
        "spring.datasource.driver-class-name=org.h2.Driver",
        "spring.datasource.username=sa",
        "spring.datasource.password="
})
class McpControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @BeforeEach
    void setup() {
        jdbcTemplate.execute("DROP TABLE IF EXISTS tasks");
        jdbcTemplate.execute("""
                CREATE TABLE tasks (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    title VARCHAR(140) NOT NULL,
                    description TEXT,
                    status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
                    priority VARCHAR(10) NOT NULL DEFAULT 'MEDIUM',
                    due_date DATE,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
    }

    @Test
    void helpEndpointWorks() throws Exception {
        mockMvc.perform(get("/mcp/help"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.tool").value("mcp-help"));
    }

    @Test
    void schemaEndpointWorks() throws Exception {
        mockMvc.perform(get("/mcp/schema/tasks"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.tool").value("mcp-schema-tasks"));
    }

    @Test
    void insertTasksWorks() throws Exception {
        String body = """
                [
                  {
                    "title": "Prepare test data",
                    "description": "Create sample tasks",
                    "status": "OPEN",
                    "priority": "HIGH",
                    "dueDate": "2026-04-05"
                  },
                  {
                    "title": "Verify summary endpoint",
                    "status": "DONE",
                    "priority": "MEDIUM"
                  }
                ]
                """;

        mockMvc.perform(post("/mcp/tasks")
                        .contentType("application/json")
                        .content(body))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.inserted").value(2));
    }

    @Test
    void summaryEndpointWorks() throws Exception {
        jdbcTemplate.update("INSERT INTO tasks(title, status, priority) VALUES ('A', 'OPEN', 'HIGH')");
        jdbcTemplate.update("INSERT INTO tasks(title, status, priority) VALUES ('B', 'DONE', 'LOW')");

        mockMvc.perform(get("/mcp/tasks/summary"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.total").value(2));
    }
}