package org.acn.mcptaskservice;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;

import static org.hamcrest.Matchers.containsString;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.delete;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.header;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@SpringBootTest
@AutoConfigureMockMvc(addFilters = false)
@TestPropertySource(properties = {
        "spring.datasource.url=jdbc:h2:mem:mcpprotocoldb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1",
        "spring.datasource.driver-class-name=org.h2.Driver",
        "spring.datasource.username=sa",
        "spring.datasource.password=",
        "app.api-key=test-key"
})
class McpProtocolControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @BeforeEach
    void setup() {
        jdbcTemplate.execute("DROP TABLE IF EXISTS tasks");
        jdbcTemplate.execute("""
                CREATE TABLE tasks (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    title VARCHAR(140) NOT NULL,
                    description TEXT,
                    status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
                    priority VARCHAR(10) NOT NULL DEFAULT 'MEDIUM',
                    due_date DATE,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
    }

    @Test
    void initialize_shouldReturnJsonRpcResponseAndSessionHeader() throws Exception {
        mockMvc.perform(post("/mcp")
                        .header("Accept", "application/json, text/event-stream")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(initializeRequest()))
                .andExpect(status().isOk())
                .andExpect(header().exists("Mcp-Session-Id"))
                .andExpect(jsonPath("$.jsonrpc").value("2.0"))
                .andExpect(jsonPath("$.result.protocolVersion").value("2025-06-18"))
                .andExpect(jsonPath("$.result.capabilities.tools.listChanged").value(false));
    }

    @Test
    void toolsList_shouldWorkAfterInitializeLifecycle() throws Exception {
        String sessionId = initializedSession();

        mockMvc.perform(post("/mcp")
                        .header("Accept", "application/json, text/event-stream")
                        .header("Mcp-Session-Id", sessionId)
                        .header("MCP-Protocol-Version", "2025-06-18")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "jsonrpc": "2.0",
                                  "id": 2,
                                  "method": "tools/list",
                                  "params": {}
                                }
                                """))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.result.tools[0].name").value("mcp_schema_tasks"))
                .andExpect(jsonPath("$.result.tools[1].inputSchema.properties.tasks.type").value("array"));
    }

    @Test
    void toolsCall_shouldInsertTasksUsingOfficialMcpShape() throws Exception {
        String sessionId = initializedSession();

        mockMvc.perform(post("/mcp")
                        .header("Accept", "application/json, text/event-stream")
                        .header("Mcp-Session-Id", sessionId)
                        .header("MCP-Protocol-Version", "2025-06-18")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "jsonrpc": "2.0",
                                  "id": 3,
                                  "method": "tools/call",
                                  "params": {
                                    "name": "mcp_tasks",
                                    "arguments": {
                                      "tasks": [
                                        {
                                          "title": "Official MCP Task",
                                          "description": "created through tools/call",
                                          "status": "OPEN",
                                          "priority": "HIGH",
                                          "dueDate": "2026-04-10"
                                        }
                                      ]
                                    }
                                  }
                                }
                                """))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.result.isError").value(false))
                .andExpect(jsonPath("$.result.structuredContent.requested").value(1))
                .andExpect(jsonPath("$.result.structuredContent.inserted").value(1));
    }

    @Test
    void normalOperations_shouldFailBeforeInitializedNotification() throws Exception {
        String sessionId = initializeSession();

        mockMvc.perform(post("/mcp")
                        .header("Accept", "application/json, text/event-stream")
                        .header("Mcp-Session-Id", sessionId)
                        .header("MCP-Protocol-Version", "2025-06-18")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "jsonrpc": "2.0",
                                  "id": 2,
                                  "method": "tools/list",
                                  "params": {}
                                }
                                """))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.error.message", containsString("notifications/initialized")));
    }

    @Test
    void getOnMcpEndpoint_shouldReturnMethodNotAllowedForBasicServer() throws Exception {
        mockMvc.perform(get("/mcp")
                        .header("Accept", "text/event-stream"))
                .andExpect(status().isMethodNotAllowed());
    }

    @Test
    void delete_shouldTerminateSession() throws Exception {
        String sessionId = initializeSession();

        mockMvc.perform(delete("/mcp")
                        .header("Mcp-Session-Id", sessionId))
                .andExpect(status().isNoContent());

        mockMvc.perform(delete("/mcp")
                        .header("Mcp-Session-Id", sessionId))
                .andExpect(status().isNotFound());
    }

    @Test
    void unknownSession_shouldReturnNotFound() throws Exception {
        mockMvc.perform(post("/mcp")
                        .header("Accept", "application/json, text/event-stream")
                        .header("Mcp-Session-Id", "missing-session")
                        .header("MCP-Protocol-Version", "2025-06-18")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "jsonrpc": "2.0",
                                  "id": 2,
                                  "method": "tools/list",
                                  "params": {}
                                }
                                """))
                .andExpect(status().isNotFound());
    }

    @Test
    void post_shouldRejectMissingSseInAcceptHeader() throws Exception {
        mockMvc.perform(post("/mcp")
                        .header("Accept", "application/json")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(initializeRequest()))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.error.message", containsString("Accept header")));
    }

    @Test
    void serverShouldAcceptJsonRpcResponsesFromClient() throws Exception {
        String sessionId = initializeSession();

        mockMvc.perform(post("/mcp")
                        .header("Accept", "application/json, text/event-stream")
                        .header("Mcp-Session-Id", sessionId)
                        .header("MCP-Protocol-Version", "2025-06-18")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "jsonrpc": "2.0",
                                  "id": 99,
                                  "result": {}
                                }
                                """))
                .andExpect(status().isAccepted());
    }

    private String initializeSession() throws Exception {
        MvcResult result = mockMvc.perform(post("/mcp")
                        .header("Accept", "application/json, text/event-stream")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(initializeRequest()))
                .andExpect(status().isOk())
                .andReturn();

        String sessionId = result.getResponse().getHeader("Mcp-Session-Id");
        assertNotNull(sessionId);
        return sessionId;
    }

    private String initializedSession() throws Exception {
        String sessionId = initializeSession();
        mockMvc.perform(post("/mcp")
                        .header("Accept", "application/json, text/event-stream")
                        .header("Mcp-Session-Id", sessionId)
                        .header("MCP-Protocol-Version", "2025-06-18")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "jsonrpc": "2.0",
                                  "method": "notifications/initialized"
                                }
                                """))
                .andExpect(status().isAccepted());
        return sessionId;
    }

    private String initializeRequest() {
        return """
                {
                  "jsonrpc": "2.0",
                  "id": 1,
                  "method": "initialize",
                  "params": {
                    "protocolVersion": "2025-06-18",
                    "capabilities": {},
                    "clientInfo": {
                      "name": "test-client",
                      "version": "1.0.0"
                    }
                  }
                }
                """;
    }
}
